// Curated Phosphor icon set for the Tahona design system (full package is 57MB
// — too large to bundle). Includes every icon the site uses today plus common
// operational-UI icons the design agent is likely to reach for. Add here when
// a new icon enters the site.
export {
  // used by the site today
  ArrowRightIcon,
  ArrowUpRightIcon,
  BooksIcon,
  CaretDownIcon,
  ChartLineUpIcon,
  ClockIcon,
  EnvelopeIcon,
  FactoryIcon,
  FileTextIcon,
  FirstAidIcon,
  GavelIcon,
  GitBranchIcon,
  ListIcon,
  PhoneIcon,
  PlugsConnectedIcon,
  RobotIcon,
  ShieldCheckIcon,
  ShieldIcon,
  TruckIcon,
  UserCheckIcon,
  WrenchIcon,
  XIcon,
  // extended operational set
  ArrowLeftIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  CaretUpIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CheckIcon,
  CheckCircleIcon,
  WarningIcon,
  InfoIcon,
  QuestionIcon,
  MagnifyingGlassIcon,
  GearIcon,
  UsersIcon,
  UserIcon,
  BuildingsIcon,
  BriefcaseIcon,
  CalendarIcon,
  ChatCircleIcon,
  ClipboardTextIcon,
  DatabaseIcon,
  FolderIcon,
  FilesIcon,
  GlobeIcon,
  LinkIcon,
  LockIcon,
  MapPinIcon,
  PaperPlaneTiltIcon,
  StackIcon,
  TableIcon,
  TagIcon,
  TargetIcon,
  LightbulbIcon,
  ListChecksIcon,
  ArrowsClockwiseIcon,
  ChartBarIcon,
  ChartPieIcon,
  CpuIcon,
  FlowArrowIcon,
  HandshakeIcon,
  KeyIcon,
  NotePencilIcon,
  PlusIcon,
  MinusIcon,
  SlidersIcon,
  DownloadIcon,
  UploadIcon,
  EyeIcon,
} from "@phosphor-icons/react";
